#!/usr/bin/env python3
"""Generate today-sky-data.json — daily sidereal positions of grahas
for the cohort year, applying Lahiri ayanamsha. Run once a month to refresh.

Output schema:
{
  "generatedAt": "2026-05-10",
  "ayanamsha": "Lahiri",
  "ayanamshaValue": 24.16,    // degrees, applied at the year midpoint
  "days": {
    "2026-05-10": {
      "sun":     {"sign":"Taurus","sIdx":1,"deg":19.4,"sanskrit":"Vrishabha"},
      "moon":    {"sign":"Aries", "sIdx":0,"deg":2.1, "sanskrit":"Mesha"},
      "mars":    {...},
      "mercury": {...},
      "jupiter": {...},
      "venus":   {...},
      "saturn":  {...},
      "rahu":    {...},
      "ketu":    {...}
    },
    ...
  }
}
"""
import ephem, json, datetime, math, os

ROOT = '/sessions/compassionate-peaceful-gates/mnt/astrology-101-companion'

SIGNS = [
    ("Aries",       "Mesha"),
    ("Taurus",      "Vrishabha"),
    ("Gemini",      "Mithuna"),
    ("Cancer",      "Karkata"),
    ("Leo",         "Simha"),
    ("Virgo",       "Kanya"),
    ("Libra",       "Tula"),
    ("Scorpio",     "Vrishchika"),
    ("Sagittarius", "Dhanu"),
    ("Capricorn",   "Makara"),
    ("Aquarius",    "Kumbha"),
    ("Pisces",      "Meena"),
]

# Lahiri ayanamsha — interpolates linearly. 24°06'13" at 2026-01-01 epoch.
# Source: standard Vedic ephemeris constants. Drift ~50.3 arcsec/yr.
LAHIRI_2026_DEG = 24.0 + 6/60 + 13/3600   # ~24.1036°

def ayanamsha(date):
    """Return Lahiri ayanamsha in degrees for a given date or datetime."""
    if isinstance(date, datetime.datetime):
        d = date.date()
    else:
        d = date
    epoch = datetime.date(2026, 1, 1)
    years = (d - epoch).days / 365.25
    return LAHIRI_2026_DEG + 50.3 * years / 3600.0

def tropical_to_sidereal(lon_deg, ay):
    s = (lon_deg - ay) % 360.0
    return s

def sign_for(lon_sidereal):
    sIdx = int(lon_sidereal // 30) % 12
    deg = lon_sidereal - sIdx * 30
    eng, sansk = SIGNS[sIdx]
    return {"sign": eng, "sIdx": sIdx, "deg": round(deg, 1), "sanskrit": sansk}

def ecliptic_lon_deg(body_factory, t):
    """Get ecliptic longitude of a body at ephem.Date t — in degrees, geocentric, of-date."""
    body = body_factory()
    body.compute(t)
    # ephem gives equatorial RA/Dec — convert to ecliptic longitude
    ec = ephem.Ecliptic(body)
    return math.degrees(ec.lon) % 360

# Rahu = Moon's mean ascending node. Use ephem's lunar node calculations.
# We compute true node via ephem's Sun/Moon orbit; for simplicity here use mean node formula.
def mean_node_deg(t):
    """Mean longitude of Moon's ascending node (Rahu) — Astronomical Algorithms p.144."""
    d = ephem.Date(t).datetime()
    JD = ephem.julian_date(t)
    T = (JD - 2451545.0) / 36525.0
    omega = 125.04452 - 1934.136261 * T + 0.0020708 * T*T + (T**3)/450000
    return omega % 360

def compute_day(date_obj):
    # Compute at noon UTC for stable sign reading (within a day, signs rarely change for slow planets)
    t = ephem.Date(datetime.datetime(date_obj.year, date_obj.month, date_obj.day, 12, 0, 0))
    ay = ayanamsha(date_obj)
    bodies = {
        "sun":     ephem.Sun,
        "moon":    ephem.Moon,
        "mars":    ephem.Mars,
        "mercury": ephem.Mercury,
        "jupiter": ephem.Jupiter,
        "venus":   ephem.Venus,
        "saturn":  ephem.Saturn,
    }
    out = {}
    for k, factory in bodies.items():
        lon = ecliptic_lon_deg(factory, t)
        sid = tropical_to_sidereal(lon, ay)
        out[k] = sign_for(sid)
    # Rahu (north node) — apply ayanamsha to mean node
    rahu_trop = mean_node_deg(t)
    rahu_sid = tropical_to_sidereal(rahu_trop, ay)
    out["rahu"] = sign_for(rahu_sid)
    # Ketu = Rahu + 180°
    ketu_sid = (rahu_sid + 180.0) % 360
    out["ketu"] = sign_for(ketu_sid)
    return out

# Generate from 30 days before today through 12 months ahead — covers cohort year
today = datetime.date.today()
start = today - datetime.timedelta(days=30)
end   = today + datetime.timedelta(days=365)

days = {}
d = start
while d <= end:
    days[d.isoformat()] = compute_day(d)
    d += datetime.timedelta(days=1)

ay_today = ayanamsha(datetime.datetime.combine(today, datetime.time(12)))
output = {
    "generatedAt": today.isoformat(),
    "ayanamsha": "Lahiri",
    "ayanamshaValue": round(ay_today, 4),
    "rangeStart": start.isoformat(),
    "rangeEnd": end.isoformat(),
    "days": days,
}

out_path = os.path.join(ROOT, 'today-sky-data.json')
with open(out_path, 'w') as f:
    json.dump(output, f, separators=(',', ':'))

# Also write a JS wrapper so the data can be loaded via <script src> on file://
js_out = os.path.join(ROOT, 'today-sky-data.js')
with open(js_out, 'w') as f:
    f.write('/* Auto-generated by scripts/generate_today_sky.py — do not edit by hand. */\n')
    f.write('window.__todaySkyData = ')
    json.dump(output, f, separators=(',', ':'))
    f.write(';\n')

# Print today as sanity check
print(f"Generated {len(days)} days · {start} → {end}")
print(f"Today's sky ({today}):")
for k, v in days[today.isoformat()].items():
    print(f"  {k:8} {v['sign']:12} ({v['sanskrit']:10}) {v['deg']:5.1f}°")
print(f"\nWrote {out_path}")
